import { ToolProvider } from "../types/tools";
import {
  GoogleIcon,
  GitHubIcon,
  NotionIcon,
  SlackIcon,
  XIcon,
  SpotifyIcon,
  LinkedInIcon,
  RedditIcon,
} from "../components/ProviderIcons";

// Centralized tools configuration for providers
export const toolsProviders: ToolProvider[] = [
  {
    id: "google",
    name: "Google",
    description: "Access Gmail and Google services",
    icon: GoogleIcon,
    scopes: [
      "https://www.googleapis.com/auth/gmail.readonly",
      "https://www.googleapis.com/auth/userinfo.profile",
      "https://www.googleapis.com/auth/userinfo.email",
      "https://www.googleapis.com/auth/gmail.send",
      "https://www.googleapis.com/auth/gmail.modify",
    ],
    enabled: true,
    tools: [],
  },
  {
    id: "github",
    name: "GitHub",
    description: "Access repositories and code",
    icon: GitHubIcon,
    scopes: ["repo"],
    enabled: true,
    tools: [],
  },
  {
    id: "notion",
    name: "Notion",
    description: "Connect your Notion workspace",
    icon: NotionIcon,
    enabled: true,
    tools: [],
  },
  {
    id: "slack",
    name: "Slack",
    description: "Integrate with Slack channels",
    icon: SlackIcon,
    scopes: [
      "channels.read",
      "channels.write",
      "groups.read",
      "groups:history",
      "groups:write",
      "im:history",
      "im:read",
      "im:write",
      "mpim:history",
      "mpim:read",
      "mpim:write",
      "users:read",
      "users:read.email",
    ],
    enabled: true,
    tools: [],
  },
  {
    id: "x",
    name: "X",
    description: "Integrate with X (Twitter)",
    icon: XIcon,
    scopes: ["tweet.read", "tweet.write"],
    enabled: true,
    tools: [],
  },
  {
    id: "spotify",
    name: "Spotify",
    description: "Integrate with Spotify",
    icon: SpotifyIcon,
    scopes: [
      "ugc-image-upload",
      "user-follow-modify",
      "playlist-modify-private",
      "playlist-modify-public",
      "user-library-modify",
      "playlist-read-collaborative",
      "user-read-currently-playing",
      "user-follow-read",
      "user-read-playback-position",
      "user-read-playback-state",
      "playlist-read-private",
      "user-read-recently-played",
      "user-top-read",
      "user-read-email",
      "user-library-read",
      "user-read-private",
      "app-remote-control",
      "streaming",
      "user-modify-playback-state",
    ],
    enabled: true,
    tools: [],
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    description: "Integrate with LinkedIn",
    icon: LinkedInIcon,
    scopes: ["w_member_social"],
    enabled: true,
    tools: [],
  },
  {
    id: "reddit",
    name: "Reddit",
    description: "Integrate with Reddit",
    icon: RedditIcon,
    scopes: [
      "read",
      "submit",
      "identity",
      "subscribe",
      "history",
      "account",
      "announcements",
      "edit",
      "flair",
      "livemanage",
      "modconfig",
      "modlog",
      "modothers",
      "modtraffic",
      "modwiki",
      "mysubreddits",
      "privatemessages",
      "report",
      "save",
      "vote",
      "wikiedit",
      "wikiread",
    ],
    enabled: true,
    tools: [],
  },
];

export default toolsProviders;
